### ISSUE TITLE
Ideas for this project?

### ISSUE THREAD

**Issue by G2G2G2G** [mcer12/Temper2-ESP32#1]
Was curious if you already had displays in mind? I've been eyeing the development progress on the versions of things like these:
https://www.aliexpress.com/item/4000360075845.html
they're pretty interesting, for this type of project you'd just have to add a SHT30 (as the sensor of choice from your old project) in a way it doesn't catch too much heat.

**Comment by mcer12** [comment]
It is done, I am just working on the firmware. I used the small 1.54" display because it's cheap :) but you can use any of the waveshare ones, they are all compatible.

**Comment by mcer12** [comment]
It doesn't really matter where you add the SHT30 as long as you measure right after wake-up. TEMPER2 draws ~14uA in deep sleep, so pretty much the datasheet value of 10uA + 3x 1uA for voltage regulators quiescent current.

**Comment by G2G2G2G** [comment]
Oh awesome, looking forward to seeing the completed version! The waveshare are quite a bit more expensive, a few more dollars on ali total and about double the price in total costs if you buy them from amazon or something. (that's why I was looking at the ttgo)

thanks though looking forward to the release

**Comment by mcer12** [comment]
Careful if you're thinking about TTGO boards, they are not very power efficient (the board you linked is using 40uA regulator, thats at least 50uA total)

**Comment by G2G2G2G** [comment]
Yea I've just been watching them for a few years, I haven't got any. I'll be waiting to see the results of your project which if it's anything like the first one (obviously I am guessing it is) it'll be great.. A lot of the aliexpress ones are embarrassing and the software is even worse.
